// NOTE: This file was auto-generated by Supabase CLI, but the env-var guards
// below were added manually to prevent a fatal crash when .env is missing
// VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY.

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// ─── Environment variables ────────────────────────────────────────

const ENV_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const ENV_SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL = ENV_SUPABASE_URL ?? 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = ENV_SUPABASE_KEY ?? 'placeholder-key';

// ─── Startup diagnostics ──────────────────────────────────────────

if (!ENV_SUPABASE_URL || !ENV_SUPABASE_KEY) {
  console.warn(
    '[Supabase Client] ⚠️  VITE_SUPABASE_URL and/or VITE_SUPABASE_PUBLISHABLE_KEY are not set in .env.\n' +
    '   Create a `.env` file in the project root with:\n' +
    '     VITE_SUPABASE_URL=https://your-project.supabase.co\n' +
    '     VITE_SUPABASE_PUBLISHABLE_KEY=your-anon-key\n' +
    '   The Supabase client will still be created, but any queries will fail until these are configured.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});